// Data Produk Hasil Integrasi 20 Item Resmi Veloce Co.
let products = [
    // --- 10 PRODUK UTAMA (PRIA) ---
    { id: 1, name: "Veloce Chrono Gold", priceIDR: 4250000, priceUSD: 235, priceEUR: 205, basePrice: 2500000, stock: 12, gender: "pria", category: "luxury", rating: 5, img: "images/veloce-chrono-gold.jpg", desc: "Jam tangan automatic dilapisi emas 18 karat dengan kaca anti gores sapphire crystal.", reviews: [] },
    { id: 2, name: "Fossil Machine Chronograph", priceIDR: 1850000, priceUSD: 102, priceEUR: 89, basePrice: 1100000, stock: 15, gender: "pria", category: "sport", rating: 4, img: "images/fossil-machine-chronograph.jpg", desc: "Bertekstur bazel bergerigi yang kokoh, dengan strap coklat tua bergaya petualang.", reviews: [] },
    { id: 3, name: "Classic Haritage Minimalist", priceIDR: 1450000, priceUSD: 80, priceEUR: 70, basePrice: 850000, stock: 20, gender: "pria", category: "classic", rating: 4, img: "images/classic-haritage-minimalist.jpg", desc: "Desain ultra tipis yang elegan dengan tali kulit asli buatan Italia.", reviews: [] },
    { id: 4, name: "Rolex Air-King Precision Vintage", priceIDR: 55000000, priceUSD: 3044, priceEUR: 2658, basePrice: 40000000, stock: 2, gender: "pria", category: "luxury", rating: 5, img: "images/rolex-air-king-precision-vintage.jpg", desc: "Arloji mekanis otomatis legendaris dengan dial abu-abu mewah dan bingkai engine-turned bertekstur garis yang langka.", reviews: [] },
    { id: 5, name: "Stealth Tactical Ranger", priceIDR: 2100000, priceUSD: 116, priceEUR: 101, basePrice: 1300000, stock: 9, gender: "pria", category: "sport", rating: 4, img: "images/stealth-tactical-ranger.jpg", desc: "Dilengkapi kompas digital, termometer, dan bodi carbon fiber yang tangguh.", reviews: [] },
    { id: 6, name: "Apple Watch Midnight", priceIDR: 1850000, priceUSD: 102, priceEUR: 89, basePrice: 1200000, stock: 14, gender: "pria", category: "sport", rating: 4, img: "images/apple-watch-midnight.jpg", desc: "Smartwatch sport yang dilengkapi fitur pelacak kebugaran, perkiraan cuaca real-time, dan sertifikasi ketahanan air. Cocok untuk aktivitas olahraga.", reviews: [] },
    { id: 7, name: "Royal Blue Dial Leather Strap", priceIDR: 7800000, priceUSD: 4317, priceEUR: 3770, basePrice: 5000000, stock: 6, gender: "pria", category: "luxury", rating: 5, img: "images/royal-blue-dial-leather-strap.jpg", desc: "Jam tangan mekanis tanpa baterai yang memadukan dial biru donker yang mewah.", reviews: [] },
    { id: 8, name: "Fossil Decker Chrono Dark Brown", priceIDR: 2450000, priceUSD: 135, priceEUR: 118, basePrice: 1600000, stock: 11, gender: "pria", category: "sport", rating: 4, img: "images/fossil-decker-chrono-dark-brown.jpg", desc: "Bezel yang dapat diputar searah untuk menghitung sisa oksigen saat menyelam.", reviews: [] },
    { id: 9, name: "Seiko Prasage Cocktail Time", priceIDR: 5400000, priceUSD: 298, priceEUR: 261, basePrice: 1250000, stock: 10, gender: "pria", category: "classic", rating: 5, img: "images/seiko-prasage-cocktail-time.jpg", desc: "Dial bertekstur sunburst berkilau indah seperti pantulan gelas koktail premium.", reviews: [] },
    { id: 10, name: "Veloce Royal Oak Steel", priceIDR: 12500000, priceUSD: 691, priceEUR: 604, basePrice: 9000000, stock: 4, gender: "pria", category: "luxury", rating: 5, img: "images/veloce-royal-oak-steel.jpg", desc: "Desain jam tangan sport-luxury dengan bezel oktagonal ikonik bermaterial besi stainless premium dan dial bertekstur kotak-kotak (tapisserie).", reviews: [] },

    // --- 10 PRODUK PELENGKAP BARU (WANITA) ---
    { id: 11, name: "Rolex Celini Gold", priceIDR: 70000000, priceUSD: 3847, priceEUR: 3383, basePrice: 60000000, stock: 7, gender: "wanita", category: "luxury", rating: 5, img: "images/rolex-celini-gold.jpeg", desc: "Memancarkan kemewahan tradisional melalui case emas bertabur permata yang anggun dan rantai bertekstur unik menyerupai sisik naga.", reviews: [] },
    { id: 12, name: "Julius Oval Leather Strap Watch", priceIDR: 1150000, priceUSD: 63, priceEUR: 55, basePrice: 850000, stock: 18, gender: "wanita", category: "classic", rating: 4, img: "images/julius-oval-leather-strap-watch.jpeg", desc: "menampilkan kesan retro-klasik yang manis lewat perpaduan case oval berwarna rose gold, dial merah marun, dan tali kulit senada.", reviews: [] },
    { id: 13, name: "Casio Baby-G Step Tracker", priceIDR: 1950000, priceUSD: 107, priceEUR: 94, basePrice: 1600000, stock: 10, gender: "wanita", category: "sport", rating: 4, img: "images/casio-baby-g-step-tracker.jpeg", desc: "Jam tangan olahraga tangguh berwarna merah muda pastel yang dilengkapi fitur hitung langkah dan ketahanan benturan tinggi.", reviews: [] },
    { id: 14, name: "Versace Palazzo Empire", priceIDR: 25000000, priceUSD: 1383, priceEUR: 1208, basePrice: 21000000, stock: 3, gender: "wanita", category: "luxury", rating: 5, img: "images/versace-palazzo-empire.jpeg", desc: "Dengan gaya fashion yang glamor dan berani dengan menonjolkan logo 3D Medusa emas di atas dial biru tua yang kontras.", reviews: [] },
    { id: 15, name: "Calvin Klein Minimal Bangle", priceIDR: 3800000, priceUSD: 210, priceEUR: 183, basePrice: 3400000, stock: 8, gender: "wanita", category: "classic", rating: 5, img: "images/calvin-klein-minimal-bangle.jpeg", desc: "Jam tangan mewah yang simpel dan timeless dengan logo ikonik ck.", reviews: [] },
    { id: 16, name: "Apple Watch Starlight", priceIDR: 3500000, priceUSD: 193, priceEUR: 169, basePrice: 3100000, stock: 12, gender: "wanita", category: "sport", rating: 4, img: "images/apple-watch-starlight.jpeg", desc: "Smartwatch premium berteknologi tinggi yang dirancang untuk pemantauan kebugaran harian.", reviews: [] },
    { id: 17, name: "Casio Vintage Digital", priceIDR: 1250000, priceUSD: 69, priceEUR: 60, basePrice: 900000, stock: 25, gender: "wanita", category: "classic", rating: 4, img: "images/casio-vintage-digital.jpeg", desc: "Jam tangan digital berukuran mini yang membawa kembali tren estetika tahun 80-an.", reviews: [] },
    { id: 18, name: "Tiffany & Co Hard Wear Link", priceIDR: 65000000, priceUSD: 3597, priceEUR: 3142, basePrice: 61000000, stock: 2, gender: "wanita", category: "luxury", rating: 5, img: "images/tiffany-&-co-hard-wear-link.jpeg", desc: "Memadukan estetika perhiasan gelang rantai rose gold yang berani dengan kemewahan faset kaca safir berbentuk kotak melengkung.", reviews: [] },
    { id: 19, name: "Geethink Bangle Wire Watch", priceIDR: 1100000, priceUSD: 60, priceEUR: 53, basePrice: 850000, stock: 30, gender: "wanita", category: "classic", rating: 4, img: "images/geethink-bangle-wire-watch.jpeg", desc: "Jam tangan dengan estetika modern-klasik yang sangat unik yang dirancang sangat minimalis.", reviews: [] },
    { id: 20, name: "Tissot Tradition Chrono Rosegold", priceIDR: 1950000, priceUSD: 107, priceEUR: 94, basePrice: 1550000, stock: 15, gender: "wanita", category: "luxury", rating: 5, img: "images/tissot-tradition-chrono-rosegold.jpg", desc: "Didesain anggun untuk wanita karir modern dengan warna rosegold yang memikat.", reviews: [] }
];